server:
  port: 8000


spring:
  application:
    name: eureka-server
  cloud:
    gateway:
      routes:
        - id: nginx-api
          uri: http://localhost:8088
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/?(?<segment>.*), /$\{segment}

        - id: http-api
          uri: http://localhost:8089
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/?(?<segment>.*), /$\{segment}

